export default[
    {
        key:'1',
        title:'管理员管理',
        icon:'administrator',
        path:'/admin/administrator',
       
    },
    {
        key:'2',
        title:'用户管理',
        icon:'user',
        path:'/admin/user'
    },
    {
        key:'3',
        title:'商品管理',
        icon:'goods',
        path:'/admin/goods'
    },
    {
        key:'4',
        title:'数据统计',
        icon:'echarts',
        path:'/admin/echarts'
    },
    {
        key:'5',
        title:'订单管理',
        icon:'order',
        path:'/admin/order'
    },
    {
        key:'10',
        title:'设置',
        icon:'set',
        path:'/admin/set'
    },
]